# Generated by Django 4.2.3 on 2023-07-13 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('course', models.CharField(max_length=50)),
                ('instrument', models.PositiveSmallIntegerField(choices=[(1, 'guitar'), (2, 'piano'), (3, 'violin'), (4, 'flute')])),
                ('performance', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('has_paid', models.BooleanField()),
            ],
        ),
    ]
