# Generated by Django 4.2.3 on 2023-07-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSchool', '0002_remove_student_instrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='instrument',
            field=models.ManyToManyField(null=True, to='appSchool.instruments'),
        ),
    ]
